### ISSUE TITLE
DazzleOptions is undefined

### ISSUE THREAD

**Issue by HosseinKurd** [akshaaatt/Media-Picker#2]
DazzleOptions Is undefined!

**Comment by akshaaatt** [comment]
Could you please share the code you're using for the implementation?

**Comment by milory13** [comment]
Because JitPack is deprecated Last build here https://jitpack.io/#com.github.akshaaatt/Media-Picker unsuccessful

**Comment by akshaaatt** [comment]
Fixed in the latest build.
