### ISSUE TITLE
Could not find com.github.akshaaatt:Media-Picker:version

### ISSUE THREAD

**Issue by adilomatom** [akshaaatt/Media-Picker#5]
My Build 
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.akshaaatt:Media-Picker:1.0.2.
  Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/akshaaatt/Media-Picker/1.0.2/Media-Picker-1.0.2.pom
       - https://jcenter.bintray.com/com/github/akshaaatt/Media-Picker/1.0.2/Media-Picker-1.0.2.pom
       - https://repo.maven.apache.org/maven2/com/github/akshaaatt/Media-Picker/1.0.2/Media-Picker-1.0.2.pom
       - https://jitpack.io/com/github/akshaaatt/Media-Picker/1.0.2/Media-Picker-1.0.2.pom

dependencies
    implementation 'com.github.akshaaatt:Media-Picker:1.0.2'
and repositories
  maven { url "https://jitpack.io" }

Also Try with 
   maven { url 'https://jitpack.io' }

**Comment by vedraj360** [comment]
Try with this 
implementation 'com.github.vedraj360:Media-Picker:1.0.5'

**Comment by akshaaatt** [comment]
Resolved in the latest build. Thanks for letting me know.

**Comment by adilomatom** [comment]
How did you Solve this Issue
you Close this issue But Can't give any update in the Gradle ore repository and again same error show when we run the project

**Comment by adilomatom** [comment]
> implementation 'com.github.vedraj360:Media-Picker:1.0.5'

But 
[From your refrance](https://github.com/vedraj360/Media-Picker)

you use this dependency

dependencies {
    implementation 'com.github.akshaaatt:Media-Picker:1.0.2'
}

and there is no result on 
 implementation 'com.github.vedraj360:Media-Picker:1.0.5'

Please  past any link of the library if any library exists that you mention in the above answer
